import json
import math

INSTRUCTIONS = [
    "LOAD_HBM",
    "MMA_SYNC",
    "STALL_THERMAL",
    "STORE_HBM"
]

class GPUSimulator:
    def __init__(self):
        self.current_temp = 45.0
        self.clock_speed = 1500
        self.allocated_blocks = []
        self.thermal_map = [45.0] * 100 
        self.sram_access = []
        
        # History of all cycles
        self.timeline = []
        self.cycle_count = 0

    def calculate_thermal_diffusion(self, heat_source_indices, heat_amount):
        new_map = self.thermal_map.copy()
        
        for idx in heat_source_indices:
            new_map[idx] += heat_amount
            
        for idx in heat_source_indices:
            row, col = divmod(idx, 10)
            neighbors = []
            if row > 0: neighbors.append(idx - 10)
            if row < 9: neighbors.append(idx + 10)
            if col > 0: neighbors.append(idx - 1)
            if col < 9: neighbors.append(idx + 1)
            
            for n in neighbors:
                new_map[n] += (heat_amount * 0.3)
        new_map = [max(35.0, t - 2.0) for t in new_map]
        self.thermal_map = new_map

    def tick(self, instruction: str, description: str):
        self.cycle_count += 1
        bank_conflict = False
        conflict_details = ""
        
        
        if instruction == "LOAD_HBM":
            # Simulate memory allocation
            new_blocks = [len(self.allocated_blocks) + i for i in range(4)]
            self.allocated_blocks.extend(new_blocks)
            
            if self.cycle_count == 1:
                self.sram_access = [{"thread_id": 0, "bank_id": 4, "address": 0}, {"thread_id": 1, "bank_id": 5, "address": 0}]
            elif self.cycle_count == 2:
                self.sram_access = [{"thread_id": 0, "bank_id": 12, "address": 1}, {"thread_id": 1, "bank_id": 12, "address": 2}]
                bank_conflict = True
                conflict_details = "Bank conflict detected on SRAM_BANK_12"
            else:
                self.sram_access = []

            # Heat generated by memory controllers
            self.calculate_thermal_diffusion([10, 11, 20, 21], 5.0)

        elif instruction == "MMA_SYNC":
            tensor_core_indices = [33, 34, 43, 44]
            self.calculate_thermal_diffusion(tensor_core_indices, 25.0)
            self.sram_access = []

        elif instruction == "STALL_THERMAL":
            self.clock_speed = 750
            self.calculate_thermal_diffusion([], 0.0) 
            self.allocated_blocks = self.allocated_blocks[:4] 
            self.sram_access = []

        elif instruction == "STORE_HBM":
            self.calculate_thermal_diffusion([80, 81, 90, 91], 3.0)
            self.allocated_blocks = [] # Cleanup
            self.sram_access = []

        max_temp = max(self.thermal_map)
        if max_temp > 95.0 and instruction != "STALL_THERMAL":
            self.clock_speed = 750
        elif instruction != "STALL_THERMAL":
            self.clock_speed = 1500 

        cycle_data = {
            "cycle": self.cycle_count,
            "instruction": instruction,
            "description": description,
            "source": "HBM_ADDR_0x1000", # Mocked for now
            "destination": "SRAM_BANK_0", # Mocked for now
            "data_payload": [1.0, 2.0],   # Mocked for now
            "hardware_state": {
                "current_temperature": round(max_temp, 1),
                "clock_speed_mhz": self.clock_speed,
                "bank_conflict": bank_conflict,
                "conflict_details": conflict_details,
                "allocated_blocks": self.allocated_blocks,
                "thermal_map": [round(t, 1) for t in self.thermal_map],
                "sram_access": self.sram_access
            }
        }
        
        self.timeline.append(cycle_data)


def run_simulation():
    print("Initializing CoreWeaver Simulation Engine...")
    gpu = GPUSimulator()

    mock_compiled_program = [
        ("LOAD_HBM", "Loading Matrix A into Shared Memory"),
        ("LOAD_HBM", "CRITICAL: Thread 0 and Thread 1 colliding on Bank 12!"),
        ("MMA_SYNC", "Tensor Cores executing Matrix Multiply-Accumulate"),
        ("STALL_THERMAL", "WARNING: Temperature exceeded 95C. Throttling clock speed."),
        ("STORE_HBM", "Writing final result matrix back to main storage")
    ]

    for instruction, description in mock_compiled_program:
        gpu.tick(instruction, description)

    final_output = {
        "simulation_metadata": {
            "kernel_name": "mock_2x2_matmul",
            "total_cycles": gpu.cycle_count,
            "thermal_threshold_celsius": 90.0
        },
        "timeline": gpu.timeline
    }

    output_path = "../frontend/src/mock_matmul.json"
    with open(output_path, "w") as f:
        json.dump(final_output, f, indent=2)
        
    print(f"Simulation complete Generated {gpu.cycle_count} cycles.")
    print(f"Data written to {output_path}")

if __name__ == "__main__":
    run_simulation()